# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=1023)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
